base_url: https://api.weixin.qq.com
method: get
url: /cgi-bin/token
headers:
  Content-Type: application/json
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0
  Accept': '*/*'
params:
  grant_type: client_credential
  appid: wxf9f152aece2b88ff
  secret: e531b9dfc90f4ed8116375132fdb2aa9
